### ISSUE TITLE
Access token request denied

### ISSUE THREAD

**Issue by henrikenquist** [CollinChaffin/psFitb1t#3] opened 2016-03-30 06:37 UTC
Sorry to bother you again!

After re-installation and wiping the registry I get the following error message after running `Get-HRdata -QueryDate "2016-03-29"` (a date containing HR data).

> The app you're trying to connect did not provide valid information to Fitbit. Please report this issue to them.
> 
> Developer information: unauthorized_client - A "Personal" application is only authorized to request access tokens from the owner of the application. 

I have gone through the authentication process, entering ClientID and re-direct (to http://localhost/psfitb1t).
I have also re-set the authentication by the `Set-FitbitOAuthTokens -Force` command to no avail.

What am I missing here?
(It worked yesterday before I started to mess with other accounts, so your code works fine on a clean system)

**Comment by CollinChaffin** [comment] 2016-03-30 12:08
I just noted an issue if you upgraded I changed the callbackURL to httpS now since fitbit began adding the red warning erroneously warning upon authorization that "your app is not secure".  Since it's a throwaway callback it is irrelevant but changing to HTTPS removes that bogus warning but also if your registry still has HTTP;// for the callbackURL, you willl receive an error.  To verify, run a query with the -VERBOSE switch with the upgraded version and look for the line stating the initial auth string being sent with a GET.  If, in that string, it shows HTTP:// on your callbackurl, that is the cause of the error as with 1.0.0.2 and later it has to be HTTPS://.  Simply re-run the Set-FitbitOAuthTokens -Force should wipe all the reg keys but perhaps in your case is it not.

Please get back to me to verify if in fact you have HTTP: on your callbackurl in the registry and -FORCE is not removing it properly and I can debug further and address it.

**Comment by henrikenquist** [comment] 2016-03-30 12:47
First I ran `Set-FitbitOAuthTokens -Force` and this works fine, just as before (sorry if I was unclear on that).
I used `https://localhost/psfitb1t` in the redirect/callbackURL as instructed and it was changed in the registry.

Great.

I then ran `Get-HRdata -QueryDate "2016-03-29" -Verbose` and got the following output (the Verbose parts):

```

VERBOSE: Token expired
VERBOSE: Auth Code is:
VERBOSE: Sending to URL https://api.fitbit.com/1/user/~/activities/heart/date...
VERBOSE: This request: Headers=
VERBOSE: Get https://api.fitbit.com/1/user/~/activities/heart/date...
```

So that seems to work (as far I understood your comment above)

Alas, I still get the same error message as reported in the first post.

EDIT:
I changed back to `http://localhost/psfitb1t` and got the same -Verbose output, i.e. `VERBOSE: Get https://api.fitbit.com/1/user/~/activities/heart/date...`

**Comment by CollinChaffin** [comment] 2016-03-30 17:28
Hmm it sure seems that if the reg keys are okay then its something on your personal app in the fitbit dev site.  Can you re-verify those settings?  The "token expired" would indicate something in the query does in fact not match on their end or what is stored on your machine is simply not accurate.  

Also, I'm not clearly understanding but if the 1st full query is successful or not - I do not see how one query with the stored token would be fully successful and then this error.  If however, you think through this switching you are doing that the reg keys are correct but then it fails to EVER get a successful query - then please go into HKCU\psfitb1t and dump ALL the values there and post them here for me to help further diagnose.

Eventually I will build more functions for profile switching and backup/restore of the config etc.

**Comment by henrikenquist** [comment] 2016-03-31 08:57
My Fitbit dev app settings are identical to those described in your instructions.

It seems that the token (API/Client secret) is never stored in the registry (full content below):

> (Standard)                     REG_SZ     (value not declared)
> psfitb1tClientID              REG_SZ     XXXXXX
> psfitb1tRedirectURL      REG_SZ     https://localhost/psfitb1t

I don't get the Fitbit login screen described in points 4 in the instructions you provided, nor the validation screen described in point 4b. It DID come up the very first time I went through this setup process some days ago, but not anymore.

Could this be it?

PS
Running the `-Force - psfitb1tClientID` switches doesn't prompt me to enter information via the commandline, as described in Example 3 provided by `Get-Help Set-FitbitOAuthTokens`

**Comment by CollinChaffin** [comment] 2016-04-01 21:23
Sorry yes what browser are you using?  I would open a tab, log in to the DEV.fitbit.com site, then specifically LOG OUT.  Then delete the reg keys and re-run.  Either way, you should have to authenticate.  Now, the options screen to click "authorize" is only once the token on their end expires, so if it hasn't been 30 days, you only need to do the first login not the authenticate portion.

If it ever works properly with a single query, then it has to be boiling down to you switching profiles and the reg keys.  If, however, you never get a working query after starting from scratch with zero reg keys set - then it is something else and can be anything from the APP set up wrong, etc.

Again, delete the reg keys (all of them delete the entire psFitb1t branch) and log out of the dev site and start over and tell me what you get.

**Comment by henrikenquist** [comment] 2016-04-05 08:56
(sorry for the late response)

I'm using IE 11.

I logged out from `dev.fitbit.com`, wiped the registry (entire psfitb1t branch), and ran `Get-HRData -QueryDate "2016-03-29"`

I got the authentication screen (ClientID and Redirect URL), but was then denied token as described above in the first post.

PS
I'm really thankful for you helping me out with this. If it works out in the end, I will spread the word (and your app) in my extended research community where this kind of software is in high demand.

**Comment by CollinChaffin** [comment] 2016-04-11 18:57
Ditto on the late response here :) Now that you wiped the reg keys and started from scratch, all I can think is a minor typo on the Fitbit app you set up would then deny the token request, but I'm not ruling out something else.

Can you post a screenshot of your psFitb1t registry key branch showing the values or post them here (you can blur/omit the ClientID if you are 100% positive it matches the Fitbit app.  I will say that I have created duplicate fitbit apps on the dev site and forgotten that each one generates a brand new "ClientID" so if you switched apps, that is the problem.

In addition to the reg values, can you please screenshot your personal fitbit app setup (the actual app config screen showing the callbackURL etc. actually does NOT show your clientID or anything sensitive (which is also why if you do not remember to back out to show the "manage your applications" to list the apps, you will not see the ClientID assiociated to that app - hence my suggestion above).

Also, re-run your query as-is but add the -VERBOSE flag please and copy that console output here as well and we'll get it figured out.

**Comment by henrikenquist** [comment] 2016-04-14 07:14
OK. Here goes:

**Registry**
![psfitb1t_registry_anon](https://cloud.githubusercontent.com/assets/13780152/14519690/c88bffd8-0220-11e6-841b-824896f2f71a.png)

**Fitbit setup**
![psfitb1t_config](https://cloud.githubusercontent.com/assets/13780152/14519705/ddb9aa68-0220-11e6-8905-30ee065606e4.PNG)

**Console output**
![psfitb1t_powershell](https://cloud.githubusercontent.com/assets/13780152/14519735/06a61aec-0221-11e6-838b-038204afc040.PNG)

**Comment by CollinChaffin** [comment] 2016-04-14 07:36
Okay only have a min then have to look more tomorrow.  It is defintely not getting back a token so it is on the fitbit side.  If you look half way down the console verbose output you can see the auth code is blank.  Right above that, I still see what you put in for your ClientID ending in Y - face value my guess is you need to go to dev fitbit site, go to "manage my applications", look at "OAuth 2.0 Client ID" and reconfirm it actually is the value ending in PRY as shown being sent above.  Then click the "reset client secret" and "revoke client access tokens" buttons and try it all again.

You may have to privately send me that first app screen showing your clientid and tokens etc if the above steps will not work, or even set up a whole new app on the dev site and start over.  Either way, the problem is 100% the clientID and auth on your system is either not getting to the fitbit site, or not matching the info on record there to get the token assigned back - or perhaps something is wrong with your account.

**Comment by henrikenquist** [comment] 2016-04-14 13:43
I have re-installed the program (latest version), and reset my system/registry, triple checked the settings everywhere imaginable, and followed your instructions like a devout disciple - but no success.

Is there a way for me to enter the token and the API secret manually? I have used the `Set-FitbitOAuthTokens - Force` for `ClientID` and `RedirectURL` but are there flags(?) for `Tokens`and `Secrets`too?

To enter them manually in the registry would also be a passable solution.

The reason I ask this is that no matter what I do, I never get the following screen back again, even when logged out from the Fitbit site:

![psfitb1t4](https://cloud.githubusercontent.com/assets/13780152/14529915/f54b0d9e-0256-11e6-8b7d-36b528444f63.png)

**Comment by CollinChaffin** [comment] 2016-04-14 15:20
Hi, if you can't clear your cookies and log out the dev fitbit site and EVER get the login screen above to pop up, it 100% has zero to do with the application and is a problem with your account because the authorization is simply never being invoked on their side.  Did you do what I asked on the app dev site and manually clicked the button to clear the tokens?  Have you set up a 2nd app?  Please do one of these two things now to troubleshoot further.  If I click the buttons to revoke my client tokens, click LOGOUT of the dev site and clear my cookies restart my browser, I am no longer authenticated and ANY query to that dev site needs to then pop up that login screen you said you are still not getting - so something bad is clearly cached somewhere and a 2nd app may help you hunt it down.

**Comment by CollinChaffin** [comment] 2016-04-14 15:22
Here's a screenshot - these are the buttons on the dev site I want you to click.
![snag_4-14-2016_10-21-09](https://cloud.githubusercontent.com/assets/9301483/14533450/c2d7ee58-022a-11e6-987b-e8f9e681ed2c.png)

**Comment by henrikenquist** [comment] 2016-04-15 08:59
I have tried both the Reset/Revoke and the second app suggestions but no success.

A little history:

Initially I synched one of the Surge devices to my private account and it seems that it is only the data from this account that is fetched by the psFitb1t app!

I then synched one Surge device to one separate Fitbit user account each for research purposes (two devices, two accounts), and have set up a psFitb1t app for each on the dev.fitbit.com site.

Troubleshooting steps:

_Logout and clear cache_
I logged out from fitbit.dev.com, cleared the browser cache, re-started the browser, and ran the Get-HRData script again. It didn't work.

_Private account_
I then logged into the dev.fitbit.com site again using my **private** account, logged out from it immediately, and then ran the Get-HRData script once more. It worked!  I got the login screen and the CSV files etc.

_Research account_
I then deleted the dev.fitbit.com app on my private account and changed the settings in the registry to match one of the research account app settings (ClientID) to see what would happen. It didn't work.

Your code is fine, but there are some funny stuff to sort out on my end. The browser cache might be one; the fact that I only get data from the original personal account is another. Could it have something to do with theFitbit Connect software (a wild guess)?

Or it could have something to do with Google, since I use Gmail accounts for all three Fitbit accounts.

I'm sorry to bother you with troubleshooting when the problems seem to be caused by my switching between multiple accounts.

**Comment by CollinChaffin** [comment] 2016-04-15 15:38
Yes, the fitbit connect software is setting cookies.  I would recommend if you want to do what you are trying and swapping accounts, that you remove their connect software or run it from an alternate machine and then clear ALL cookies and reboot.  You should never have to "delete" any of the apps you set up on the fitbit dev site just to swap which you are using.  Just remember, the same account for which you need to pull the HR data MUST BE the same account used to log in to the dev.fitbit.com site and see the app that then correlates to the CLIENTID being used to pull the data.

So, go back and start over and go step by step to separate everything.  
1. Delete connect software with proper uninstall - reboot.
2. Clear all cookies, delete the entire psFitb1t registry branch - reboot.
3. Select Private account:
4. Log in to dev.fitbit.com and delete all defined apps you are trying with psFitb1t
5. Create brand new app with new ClientID - verify it is the ONLY app
6. LOG OUT OF dev.fitbit.com!!
7. Open task mgr verify your browser is really closed and then re-clear cookies
8. Just execute the 1st Get-HRdata query - no need to even run the other command
9. When prompted, authorize with PRIVATE account on auth popup
10. Verify query runs and token assigned
11. If successful, highlight the psFitb1t reg branch and do an EXPORT to a reg file to use later

Repeat steps 2-11 above using the RESEARCH account and if both set ups were successful, I just tested the above and literally every other run I can double-click the exported REG file on either account and run alternating queries for either account.  As for dual accounts, like I said that is separate feature request and I may address it soon when I have time but if you follow the above steps I see no reason you cannot simplify things and make 2 accounts work fairly easily.

Let me know once you have made some progress.

Thanks.

Collin

**Comment by henrikenquist** [comment] 2016-04-21 08:07
Thanks for this detailed instructions! I followed them meticulously.

Everything worked out just fine for my _Private_ account, the one I originally used when registering the Fitbit Connect software etc.

When proceeding with another account (_Research_) I got the following message after running the `Get-HRData` query in step 8:

![psfitb1t_unauth_warning](https://cloud.githubusercontent.com/assets/13780152/14701940/27e1d3a4-07a8-11e6-8e1d-cf1bcdaca730.PNG)

It seems to me that there is some cached account information regarding my _Private_ account hidden somewhere although I have:
- uninstalled the Fitbit Connect software (including reboot)
- logged out from the dev.fitbit.com site after each step (and closed the browser)
- cleared the Internet Explorer cookies (all stored information actually, including passwords etc), and
- removed the registry for psFitB1t (which I don't think is the problem here)

Odd indeed.

**Comment by CollinChaffin** [comment] 2016-04-21 18:53
Yes, but the above screen is absolutely what I would expect if a cookie was still set or your browser quietly stuck open and authenticated to the DEV site with the PRIVATE account and then trying to access the RESEARCH account's APP using it's clientid.  In other words, for some reason whether it was an expired token etc, the website auth was opened to do the once per 30 day approval required to get that token, but finding that the app's ClientID being passed wasn't in fact even in the list of apps on the server side.

So, like I said I can bounce accounts but here in lies the big issue with easily making a GUI that flip-flops between mult accounts - not only do all the reg keys on the client side need to change per attempt - but then all login cookies and browser sessions to DEV.fitbit.com also need to be totally, 100% cleared and inactive between each run.  It looks to me like that 2nd part just didn't happen in your test and you should maybe try like ccleaner to flush your cookes and then go one step further and actually reboot in between flip flopping the reg keys/accounts as a test - then you should see it work.

**Comment by CollinChaffin** [comment] 2016-04-21 18:56
Also not that I doubt your abilities but I often overlook the obvious - are you absolutely certain of that RESEARCH account's CLIENTID and on that account did you absolutely flush/clear the tokens online and then note that it should have changed that CLIENTID and then you MUST discard 100% of all reg keys/values/info that you had been using on that RESEARCH account once you do the "REVOKE".....that may also cause the above error if you did not - just an idea.

**Comment by henrikenquist** [comment] 2016-04-22 12:08
**I apologize**

When I deleted the cookies etc in the browser, the option was to DELETE the saved data for all items EXCEPT for the first item at the top, where the option was to KEEP the saved data - thank you Microsoft for the consistency of the user interface in IE.

You can close this isse since it all works exactly as you said. I use your method of saving the registry entries for each account and it works like a charm!

And you were right regarding another thing - the devil is in the detail

![psfitb1t_cookies](https://cloud.githubusercontent.com/assets/13780152/14740974/27517da4-0893-11e6-89cb-c190d2962c76.PNG)

**Comment by CollinChaffin** [comment] 2016-04-25 00:30
Awesome!  I'm so glad we went through this though because it helps others, right?  :)

I will close it and let me know if you have any other issues.  Hopefully soon I'll get a bit more time and begin working on additional improvements!

**Closed as completed by CollinChaffin** 2016-04-25 00:30 UTC
